### ISSUE TITLE
No existing Rich Text in the editor when editing an event that has Rich Text content in it

### ISSUE THREAD

**Issue by sasch-a** [veldtech/partyverse-issues#2]
It is possible to copy the text on the page into the editor, but for the average user this will be experienced as an inconvenience in which they think they can no longer edit their event without losing all of their text.

**Event Link:** https://partyverse.app/events/23689

### Event with Rich Text in it.
![image](https://user-images.githubusercontent.com/16175575/167772516-86333a16-4ddc-4d47-a8de-8fa298b16f55.png)

### Trying to edit it shows nothing in the editor.
![image](https://user-images.githubusercontent.com/16175575/167772588-792a31a9-7a41-45f5-bde8-3a21267b4a9d.png)

**Comment by velddev** [comment]
This was fixed :)
